"""baseline2

Revision ID: 9e226007d06f
Revises: b4d36d877172
Create Date: 2019-08-29 21:36:56.017271

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9e226007d06f'
down_revision = 'b4d36d877172'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Hobby Name')
    op.drop_table('User Hobbies')
    op.drop_table('User')
    op.drop_table('Match')
    op.drop_table('Votes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Votes',
    sa.Column('USERONEID', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('USERTWOID', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('VOTE', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('TIMESTAMP', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['USERONEID'], ['User.ID'], name='ONE'),
    sa.ForeignKeyConstraint(['USERTWOID'], ['User.ID'], name='TWO')
    )
    op.create_table('Match',
    sa.Column('MATCHID', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('USERIDONE', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('USERIDTWO', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('MATCHTIME', postgresql.TIME(timezone=True, precision=6), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['USERIDONE'], ['User.ID'], name='ONE'),
    sa.ForeignKeyConstraint(['USERIDTWO'], ['User.ID'], name='TWO'),
    sa.PrimaryKeyConstraint('MATCHID', name='Match_pkey')
    )
    op.create_table('User',
    sa.Column('ID', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('EMAIL', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('PHONE', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('NICKNAME', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('LASTNAME', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('GOOGLEID', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('GOOGLENAME', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('ID', name='User_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('User Hobbies',
    sa.Column('USERID', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('CLASSIFICATION', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('HOBBYID', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['HOBBYID'], ['Hobby Name.HOBBYID'], name='HOBBYID'),
    sa.ForeignKeyConstraint(['USERID'], ['User.ID'], name='USERID')
    )
    op.create_table('Hobby Name',
    sa.Column('HOBBYID', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('NAME', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('HOBBYID', name='HOBBYNAME_pkey')
    )
    # ### end Alembic commands ###
